ansible_user: ubuntu
ansible_ssh_private_key_file: /home/ubuntu/.ssh/yc-diplom
ansible_python_interpreter: /usr/bin/python3
ansible_become: true
ansible_become_method: sudo

common_packages:
  - curl
  - wget
  - vim
  - git
  - ca-certificates
  - apt-transport-https
  - gnupg
  - software-properties-common

nginx_listen_port: 80
nginx_site_root: /var/www/yc-diplom
nginx_site_name: yc-diplom

zabbix_version: "7.0"
zabbix_repo_deb: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu22.04_all.deb"

zabbix_server_db_name: "CHANGE_ME"
zabbix_server_db_user: "CHANGE_ME"
zabbix_server_db_password: "CHANGE_ME"
zabbix_root_db_password: "CHANGE_ME"

zabbix_server_fqdn: "zabbix.ru-central1.internal"
zabbix_server_ip: "10.10.10.30"

zabbix_agent_server: "10.10.10.30"
zabbix_agent_serveractive: "10.10.10.30"

elastic_stack_version: "9.3.1"

elasticsearch_private_ip: "10.10.20.32"
kibana_private_ip: "10.10.11.27"

elasticsearch_download_url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elastic_stack_version }}-amd64.deb"
kibana_download_url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ elastic_stack_version }}-amd64.deb"
filebeat_download_url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ elastic_stack_version }}-amd64.deb"

filebeat_setup_host: "web-a.ru-central1.internal"

elasticsearch_docker_image: "docker.elastic.co/elasticsearch/elasticsearch:9.3.1"
kibana_docker_image: "docker.elastic.co/kibana/kibana:9.3.1"
filebeat_docker_image: "docker.elastic.co/beats/filebeat:9.3.1"

