all:
  children:
    bastion:
      hosts:
        bastion.ru-central1.internal:

    web:
      hosts:
        web-a.ru-central1.internal:
        web-b.ru-central1.internal:

    zabbix:
      hosts:
        zabbix.ru-central1.internal:

    elastic:
      hosts:
        elastic.ru-central1.internal:

    kibana:
      hosts:
        kibana.ru-central1.internal:
